### ISSUE TITLE
QML deployment

### ISSUE THREAD

**Issue by TheAssassin** [linuxdeploy/linuxdeploy-plugin-qt#1]
The last bit that is really missing functionality wise to implement the same functionality linuxdeployqt provides is the deployment of QML files.

I would like to combine both the QML related code in linuxdeployqt (e.g., https://github.com/probonopd/linuxdeployqt/blob/master/tools/linuxdeployqt/shared.cpp#L1513), with the script that @azubieta's Nomad software center uses to bundle its QML dependencies (https://github.com/nomad-desktop/nx-software-center/blob/master/build_scripts/appimage.include.qml.modules.py#L99).

Any help is appreciated. CC @azubieta @probonopd

**Comment by azubieta** [comment]
Just let me finish https://github.com/azubieta/appimage-releases-indexer and I'll gladly take care of it. It's not quite complicated. qmlimportscanner does most of the work we just have to parse it's output and copy the qml modules into the AppDir.

**Comment by azubieta** [comment]
We must provide to our user the possibility of specifying additional "QML Modules search paths".
What do you prefer?
- a command line argument
- an environment variable

**Comment by azubieta** [comment]
WIP at [qml_support branch](https://github.com/linuxdeploy/linuxdeploy-plugin-qt/tree/qml_support).

**Comment by probonopd** [comment]
`linuxdeployqt` allows to pass in multiple `-qmldir` arguments.

**Comment by azubieta** [comment]
We will be using an environment variable for this goal named `EXTRA_QML_IMPORT_PATHS`.
It will receive as value a colon separated string list. 

By example:
`export EXTRA_QML_IMPORT_PATHS="/opt/qt5/qml:/opt/plasma5/"`

**Comment by azubieta** [comment]
Update report.
Geting the following error while calling
https://github.com/linuxdeploy/linuxdeploy-plugin-qt/blob/b5094b23e4a4fb07e8d66b94d4317712be3760be/src/util.h#L26 
```
Calling: /usr/bin/qmlimportscanner  -rootPath  /home/alexis/Workspace/linuxdeploy-plugin-qt/tests/QtQuickControls2Application/  -rootPath  /home/alexis/Workspace/linuxdeploy-plugin-qt/tests/QtQuickControls2Application/build/AppDir  -importPath  /usr/lib/x86_64-linux-gnu/qt5/qml  
free(): invalid next size (normal)
```

**Comment by TheAssassin** [comment]
I'm not so sure about this "let's bundle an entire Qt application for testing the QML support" part of your branch. It's a lot of bloat that is forcibly shipped there...

**Comment by azubieta** [comment]
Me neither but we need it to test it. We can drop it before merge. By the way, linuxdeployqt has several.
