### ISSUE TITLE
Compatibility with probonopd/linuxdeployqt

### ISSUE THREAD

**Issue by vadi2** [linuxdeploy/linuxdeploy-plugin-qt#104]
Is this in any way compatible with https://github.com/probonopd/linuxdeployqt or does using this require changing over to https://github.com/linuxdeploy/linuxdeploy-plugin-qt as well?

**Comment by TheAssassin** [comment]
It's not compatible as in "drop-in replacement". linuxdeploy, together with its Qt plugin, however form a fully functional substitute for linuxdeployqt. You need to use both. It's not hard at all. Plus, the plugin system allows much more complex deployments with much less manual effort.

**Comment by TheAssassin** [comment]
P.S.: All you need to do is download both linuxdeploy and the Qt plugin, make them executable, then rewrite the linuxdeployqt call to use linuxdeploy instead. Examples can be found in the AppImage docs https://docs.appimage.org/packaging-guide/from-source/index.html.
