### ISSUE TITLE
[qt/stdout] ERROR: Could not find Qt modules to deploy

### ISSUE THREAD

**Issue by txtsd** [linuxdeploy/linuxdeploy-plugin-qt#105]
[Link to GitHub Actions log](https://github.com/txtsd/PolyMC/runs/5084311958?check_suite_focus=true#step:13:7470)

Qt is installed via the [jurplel/install-qt-action@v2](https://github.com/jurplel/install-qt-action) action.

linuxdeploy seems to find the correct qmake, but breaks shortly after.

**Comment by TheAssassin** [comment]
There's not a single `libQt5*.so*` deployed by linuxdeploy to the AppDir. Why are you using the Qt plugin at all?

**Comment by txtsd** [comment]
The app is built with Qt. What am I doing wrong?

**Comment by txtsd** [comment]
My app structure was incorrect.
