### ISSUE TITLE
How to change qt versions

### ISSUE THREAD

**Issue by UltraBlackLinux** [linuxdeploy/linuxdeploy-plugin-qt#106]
Hey there,
I'm trying to build an appimage but there are many problems. Among them is the fact that there seems to be no way to force this plugin to use qt6. It always defaults to qt5.
How do I do this?
Thanks!

**Comment by TheAssassin** [comment]
Have you tried to set the `QMAKE` environment variable to the Qt 6 one?

**Comment by UltraBlackLinux** [comment]
> Have you tried to set the `QMAKE` environment variable to the Qt 6 one?

I'm not using Qmake, but Cmake. I don't know, how I would set that up there, because currently I'm just linking the qt libraries to my files. I tried QMake before, but it was horribly overcomplicated since CMake could do it much easier.

In case this still makes a difference I will try it

**Comment by TheAssassin** [comment]
We use `qmake` to detect paths to Qt resources. I also exclusively use CMake as a build system.

**Comment by UltraBlackLinux** [comment]
Oh okay, setting `QMAKE=/usr/bin/qmake6` worked, but now I'm having trouble with the appimage plugin - Adding `-p appimage --output appimage` errors, because it is a plugin, but using just `--output appimage` doesn't work, because appimage isn't a plugin - I'm confused about this one...

**Comment by UltraBlackLinux** [comment]
Well whatever, I got it to work after manually running the packing appimage. I wonder if I even need that or if appimagetool will suffice. Thanks for your help regardless!

**Comment by TheAssassin** [comment]
It may run locally, but it likely won't run in a vanilla VM. Better try with some Ubuntu, openSUSE etc. VMs to make sure it won't fail.

Are you running this plugin *standalone*? You need to use linuxdeploy with `--plugin qt [...] --output appimage`. Again, this is a *plugin*.

**Comment by UltraBlackLinux** [comment]
> It may run locally, but it likely won't run in a vanilla VM. Better try with some Ubuntu, openSUSE etc. VMs to make sure it won't fail.
> 
> Are you running this plugin _standalone_? You need to use linuxdeploy with `--plugin qt [...] --output appimage`. Again, this is a _plugin_.

I ran it like one should use plugins. Maybe I shouldn't have added another `-p appimage`, the cli lib might not support it

**Comment by TheAssassin** [comment]
`-p appimage` is and has always been wrong. `-p` is for input plugins like Qt. Please post your complete command line (redact personal information, though).

**Comment by UltraBlackLinux** [comment]
> `-p appimage` is and has always been wrong. `-p` is for input plugins like Qt. Please post your complete command line (redact personal information, though).

Welp I got it to work. This whole plugin situtation is a bit confusing at first.

**Comment by TheAssassin** [comment]
The README and the linuxdeploy docs are pretty clear about it, though. But anyway. Next time please feel free to seek for help earlier. Glad it's working now. We need more Qt 6 testers.
