### ISSUE TITLE
Remove bundling Gtk platform plugins

### ISSUE THREAD

**Issue by probonopd** [linuxdeploy/linuxdeploy-plugin-qt#109]
https://github.com/linuxdeploy/linuxdeploy-plugin-qt/blob/43c69b060afd33a7b9da0114251591d09b5066df/src/deployers/PlatformPluginsDeployer.cpp#L56-L62

Apparently I had been too optimistic at that time.

Bundling Gtk platform plugins created _lots_ of hassle, including 

- https://github.com/AppImage/AppImageUpdate/issues/145
- https://github.com/AppImage/AppImageUpdate/issues/149
- https://github.com/AppImage/AppImageUpdate/issues/150
- https://github.com/AppImage/AppImageUpdate/issues/151
- https://github.com/AppImage/AppImageUpdate/pull/152
- https://github.com/AppImage/AppImageUpdate/issues/161
- https://github.com/AppImage/AppImageUpdate/issues/166

Please remove the bundling of those.

**Comment by vadi2** [comment]
What is the side effect of removing them?

**Comment by TheAssassin** [comment]
"Native look" may be gone. But that is overrated anyway. Maybe we can just bundle some standard style like Fusion and make apps use that as a default (unless they change it themselves).

Some apps deliberately delete these files already.

**Comment by probonopd** [comment]
> "Native look" may be gone

Only on Gtk based desktops like Gnome, not on Qt based ones like KDE Plasma.

**Comment by TheAssassin** [comment]
Even Xfce seems to use Fusion nowadays, not Gtk+, at least for many AppImages I came across. As said, "native look" is overrated...

I think that Gtk+ platform theme bundling stuff was and still is experimental and has shown to cause more issues than it solves. I'll remove them soon.

**Comment by vadi2** [comment]
It's definitely a loss to have this gone, native look is not overrated and very much desired. It's one of It's biggest weakness on Linux that it does not integrate well with the users visual environment, unless they happen to be on KDE.

**Comment by probonopd** [comment]
Not really a loss since it was not working and caused a lot of trouble for many people over the years. Just look at the many bug reports linked above. What is worse - the application not working or the application not looking like Gtk applications? (Personally I am trying to avoid Gtk applications altogether.)

**Comment by vadi2** [comment]
I haven't seen such reports from my users. Please recommend a method to undo this as an opt-in.

**Comment by TheAssassin** [comment]
@vadi2 if you send a PR to make this opt-in, I'll happily merge it. The `PlatformPluginDeployer` already shows how this needs to be done. I think if you, as the author, decide you want to enable such an experimental feature, that's completely acceptable. We just need to communicate it's an experiment, and give responsibility into the AppImage author's hands.
