### ISSUE TITLE
Gstreamer not deployed correctly for Qt app on Ubuntu 20

### ISSUE THREAD

**Issue by martinrotter** [linuxdeploy/linuxdeploy-plugin-qt#125]
Here is app debug log: [justpaste.it/62wg2](https://justpaste.it/62wg2)
Here is build script where you can see how app was compiled and how "linuxdeploy" was executed: https://github.com/martinrotter/rssguard/blob/master/resources/scripts/github-actions/build-linux-mac.sh#L69
Here is build log: https://github.com/martinrotter/rssguard/runs/8222561212?check_suite_focus=true

I honestly tried and tinkered with this for 2 hours and was unable to bundle gstreamer even manually. It just seems that plugin does not really work. RSS Guard is OSS and you can easily compile/test by yourself.

Symptom seen is that Qt class with gstreamer backend (QSoundEffect) cannot play sounds - no sounds are heard because of "No audio device detected" (see log).

Thanks.

**Comment by hcorion** [comment]
Have you tried using https://github.com/linuxdeploy/linuxdeploy-plugin-gstreamer

**Comment by TheAssassin** [comment]
Unfortunately, no response was provided in the last months. I also think @hcorion's suggestion of adding the GStreamer plugin should do the trick. If not, please don't hesitate to comment (and reopen).
