### ISSUE TITLE
boost::filesystem::copy_file error in github actions

### ISSUE THREAD

**Issue by drunkbatya** [linuxdeploy/linuxdeploy-plugin-qt#128]
A few days ago, without any changes, our CI/CD process crushed at linuxdeploy step with lots of errors like the one below:
```bash
...
[qt/stdout] ERROR: Failed to copy file /usr/share/doc/qt515graphicaleffects/copyright to AppDir/usr/share/doc/qt515graphicaleffects/copyright: boost::filesystem::copy_file: Invalid cross-device link: "/usr/share/doc/qt515graphicaleffects/copyright", "AppDir/usr/share/doc/qt515graphicaleffects/copyright" 
[qt/stdout] Copying file /usr/share/doc/qt515imageformats/copyright to AppDir/usr/share/doc/qt515imageformats/copyright 
[qt/stdout] ERROR: Failed to copy file /usr/share/doc/qt515imageformats/copyright to AppDir/usr/share/doc/qt515imageformats/copyright: boost::filesystem::copy_file: Invalid cross-device link: "/usr/share/doc/qt515imageformats/copyright", "AppDir/usr/share/doc/qt515imageformats/copyright" 
[qt/stdout] Copying file /usr/share/doc/qt515quickcontrols2/copyright to AppDir/usr/share/doc/qt515quickcontrols2/copyright 
[qt/stdout] Copying file /usr/share/doc/qt515svg/copyright to AppDir/usr/share/doc/qt515svg/copyright 
[qt/stdout] ERROR: Failed to copy file /usr/share/doc/qt515svg/copyright to AppDir/usr/share/doc/qt515svg/copyright: boost::filesystem::copy_file: Invalid cross-device link: "/usr/share/doc/qt515svg/copyright", "AppDir/usr/share/doc/qt515svg/copyright" 
[qt/stdout] ERROR: Failed to execute deferred operations 
ERROR: Failed to run plugin: qt (exit code: 1) 
Error: Process completed with exit code 1.
```

As I understand I have a problem with Boost C++ library which GitHub has updated on its runners. I wonder if forcing to downgrade libboost could solve this?

**Comment by TheAssassin** [comment]
Things got better after replacing Boost's filesystem implementation with C++17's native STL implementation. This specific bug doesn't seem to occur any more. However, the tests do not complete successfully. Checking what's wrong.

**Comment by TheAssassin** [comment]
Should be fixed, closing therefore. In case the issue persists, please re-open and/or comment.

**Comment by drunkbatya** [comment]
As i see, issue isn't fixed in latest releases: https://github.com/flipperdevices/qFlipper/actions/runs/3150719719/jobs/5123829161#step:7:3674.
The output hasn't changed.

**Comment by TheAssassin** [comment]
This makes no sense. The latest continuous release is not using boost anymore. Checking.

By the way, this reminds me I wanted to make the Qt plugin print its version on every invocation.

**Comment by drunkbatya** [comment]
I'm sorry, the last problem was in github action's docker cache, now it works like a charm, thanks!

**Comment by TheAssassin** [comment]
Great! linuxdeploy-plugin-qt also prints a version number starting with the last continuous release, so we can easily check whether it's outdated from now on.
