### ISSUE TITLE
build with qt6.3.2 throw error

### ISSUE THREAD

**Issue by xiaoyifang** [linuxdeploy/linuxdeploy-plugin-qt#132]
got the error.
```
[qt/stdout] Deploying dependencies for ELF file /home/runner/work/goldendict/Qt/6.3.2/gcc_64/plugins/position/libqtposition_nmea.so 
[qt/stdout] ERROR: Could not find dependency: libQt6SerialPort.so.6 
```

but the application does not dependent on libQt6SerialPort

**Comment by TheAssassin** [comment]
Obviously, the position plugin needs `libQt6SerialPort` which means your application depends on `libQt6SerialPort`. It's just not visible with `ldd` since plugins are loaded dynamically with `dlopen`.
