### ISSUE TITLE
Qt 6.4 SQL Plugin metadata gets removed when copying to appdir

### ISSUE THREAD

**Issue by XERGER** [linuxdeploy/linuxdeploy-plugin-qt#133]
Hey,

i am trying to use linuxdeploy with qt and appimage.

My app requires the qt sql plugins.

When creating the  appDir with linuxdeploy the plugins get copied to the appdir but lose their metadata so the QPluginLoader can not read them anymore.

I checked the linuxdeploy code it is using std::filesystem::copy to copy the files i dont know how that could remove the metadata.

"[qt/stdout] Copying file /opt/Qt/6.4.0/gcc_64/plugins/sqldrivers/libqsqlmysql.so to /app/tmp/deployment/linux/InformationServer/usr/plugins/sqldrivers/libqsqlmysql.so"

so workaround: if i just use linuxdeploy & linuxdeploy-plugin-qt to create the appdir and afterwards copying the opt/Qt/6.4.0/gcc_64/plugins/sqldrivers/libqsqlmysql.so manually into the appdir replacing the in plugin folder existing files and using appimagetool as standalone to create the appimage everything is working just fine.

![driver not loaded](https://user-images.githubusercontent.com/48217414/211062485-6b1db5cb-b3b0-4884-b24d-7c9dbfd1e321.png)
![plugin_not_loaded](https://user-images.githubusercontent.com/48217414/211062499-4a6a06a3-b77f-45e0-b447-d91966812cc2.png)
![grafik](https://user-images.githubusercontent.com/48217414/211066972-a71df4ab-f5a1-4141-a5a0-351b2068ede9.png)
![grafik](https://user-images.githubusercontent.com/48217414/211067149-d9cc56ed-800a-4297-8b6f-c55e08f5f2fa.png)

**Comment by TheAssassin** [comment]
Need a log.

**Comment by adazem009** [comment]
@TheAssassin I have the same problem with my application. I've got a workflow (on Ubuntu 20.04) which creates AppImages for Qt 5.12, 5.15 and 6.5.1. Qt 5 AppImages are working fine. However, the Qt 6.5.1 AppImage fails to start with the same error as on the screenshot. The problem seems to be that `patchelf` removes the plugin metadata when changing the rpaths.
Surprisingly, I can create a working AppImage on Ubuntu 22.04. I'm not sure why this only happens on 20.04.

Read this for more info about this: https://forum.snapcraft.io/t/cannot-use-qt6-in-classic-core22-snap/34771

**Comment by TheAssassin** [comment]
Why are you even using Ubuntu's patchelf at all?

**Comment by adazem009** [comment]
> Why are you even using Ubuntu's patchelf at all?

I'd like to build linuxdeploy and linuxdeploy-plugin-qt myself without downloading any prebuilt AppImages so that I can support more CPU architectures in the future. Should I build patchelf as well instead of using the distribution package?

**Comment by TheAssassin** [comment]
We actually bundle patchelf in our official binaries for a reason. They pin a specific version we know work fine. So if you want to build everything yourself, please make sure to use a suitable patchelf. You can find some orientation in this repository's `ci` subdirectory.
