### ISSUE TITLE
Add environment variable EXTRA_QT_PLUGINS

### ISSUE THREAD

**Issue by TheAssassin** [linuxdeploy/linuxdeploy-plugin-qt#14]
At the moment, when running the Qt plugin from linuxdeploy, users cannot specify extra Qt plugins, this is only possible through a [CLI parameter](https://github.com/linuxdeploy/linuxdeploy-plugin-qt/blob/master/src/main.cpp#L285). We should add an environment variable, like we do for all other user configuration.

**Comment by TheAssassin** [comment]
CC @Marcus10110

**Comment by Marcus10110** [comment]
Would this be best done by using `getenv` for `EXTRA_QT_PLUGINS`, splitting the contents into a vector based on a delimiter `{",", ";"," "}` and and combining that with `extraPlugins.Get()` and passing that into the system that populates `extraQtModules`?
https://github.com/linuxdeploy/linuxdeploy-plugin-qt/blob/master/src/main.cpp#L285
https://github.com/linuxdeploy/linuxdeploy-plugin-qt/blob/master/src/main.cpp#L377
I was planning on bypassing the issue by just manually copying the required plugins in my packaging script, but it might be quick to open a PR with this.

**Comment by TheAssassin** [comment]
@Marcus10110 that's exactly what I did yesterday, but forgot to commit & push. I CC'd you primarily to inform you I'm working on this, after you left on IRC.
