### ISSUE TITLE
building for arm

### ISSUE THREAD

**Issue by iltommi** [linuxdeploy/linuxdeploy-plugin-qt#151]
Since the linuxdeploy is now working for arm (big thanks!) I tried to compile the qt plugin, but run into some problem.
I start with a arm fedora 34:
```
docker run --rm -i -t --platform linux/arm64 arm64v8/fedora:34 /bin/bash
```

then I do this to compile:
```
dnf -y install gcc gcc-c++ qconf libtiff-devel gsl-devel redhat-lsb-core blas-devel pandoc hdf-devel hdf5-devel cfitsio-devel fftw3-devel rpm-build qt6-* git wget patchelf CImg-devel libpng libjpeg libz locate

cd
git clone https://github.com/nlohmann/json
cd json
mkdir build
cd build/
cmake ..
make -j2 install

cd
git clone --recurse-submodules https://github.com/linuxdeploy/linuxdeploy-plugin-qt.git
cd linuxdeploy-plugin-qt
mkdir build
cd build/
cmake .. -DBUILD_TESTING=OFF -DSTATIC_BUILD=On
make -j2 install
```

and it fails at the end with:

```
[ 95%] Linking CXX executable ../bin/linuxdeploy-plugin-qt
/usr/bin/ld: cannot find -lpng16
/usr/bin/ld: cannot find -lz
/usr/bin/ld: cannot find -ljpeg
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lstdc++
/usr/bin/ld: cannot find -lm
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/linuxdeploy-plugin-qt.dir/build.make:162: bin/linuxdeploy-plugin-qt] Error 1
make[1]: *** [CMakeFiles/Makefile2:646: src/CMakeFiles/linuxdeploy-plugin-qt.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

Since it's probably a stupid error I run into, would it be possible to add the arm version of the plugin or it needs a big and deep work?

Thanks

**Comment by TheAssassin** [comment]
Working on official builds right now.

I have no idea why you have all these linking issues. You may need to install the corresponding packages. I cannot tell from the little bit of log you shared if that's the right advice. If the issue persists once official builds are available (and you even want to build your own builds then), you need to provide way more information such as a complete build log and details on your build system.

**Comment by iltommi** [comment]
I understand, it's a bit odd because I have almost all of those libs in `/usr/lib64`:
`libc.so  libjpeg.so  libm.so  libpng.so  libpthread.so  libz.so`
It's missing the `libstdc++` (which is there as `/usr/lib64/libstdc++.so.6.0.29` but missing the symlink) 

Anyway since you're working on that I'm going to close this issue. 

Thanks a lot

**Comment by TheAssassin** [comment]
> but missing the symlink

That could be the lack of a `dev(el)` package.
