### ISSUE TITLE
translations should be copied

### ISSUE THREAD

**Issue by tastytea** [linuxdeploy/linuxdeploy-plugin-qt#16]
linuxdeploy-plugin-qt puts translations into `usr/translations` and `QLibraryInfo::location(QLibraryInfo::TranslationsPath)` returns that path.

Since Qt translations are not normally put into /usr/translations (as far as I know), they should be automatically copied there.

**Comment by TheAssassin** [comment]
Are you requesting to copy files into the _system_?

**Comment by tastytea** [comment]
No, I meant inside the AppDir/AppImage. Normally, a build script for a Qt application would install translations into `$prefix/share/qt5/translations`, `linuxdeploy-plugin-qt` installs them into `usr/translations` and tells Qt to look only there.

Solution 1 is to modify the build script to copy translations to `${prefix}/translations` if building an AppImage. Solution 2 is having `linuxdeploy-plugin-qt` copy all .qm-files in the AppDir to `usr/translations`.

I prefer solution 2 because the current behavior is unintuitive.

**Comment by TheAssassin** [comment]
> Solution 2 is having linuxdeploy-plugin-qt copy all .qm-files in the AppDir to usr/translations.

As in, searching in "well known directories" like `usr/share/qt5/translations` and moving/symlinking files to `usr/translations`?

We could also just deploy translations to `usr/share/qt5/translations`, but then we should do it with all Qt files. CC @probonopd

**Comment by probonopd** [comment]
To be consistent, I'd choose the first of the two suggested solutions.

**Comment by TheAssassin** [comment]
I'd rather introduce an environment variable to control that behavior a bit (as in, enable on demand).

**Comment by TheAssassin** [comment]
So, rather, opt-out?

**Comment by probonopd** [comment]
Yes, if at all.

**Comment by TheAssassin** [comment]
@tastytea do we need to replicate directory structures, or can we just look for all files with that filename extension and create symlinks?

Also, how to resolve name collisions?

**Comment by tastytea** [comment]
@TheAssassin I have never seen sub-directories inside Qt's translation path, but as far as I know it is not strictly forbidden.

I would say it is highly unlikely that name collisions occur, since the only files linuxdeploy-plugin-qt puts into `usr/translations` are `qt_??.qm` and `qtbase_??.qm`, it seems.

**Comment by TheAssassin** [comment]
I meant collisions between projects, dependencies, etc. Would it be safe to rename the files automatically using some algorithm?

**Comment by tastytea** [comment]
Wouldn't the files collide long before linuxdeploy is involved?

**Comment by TheAssassin** [comment]
Not necessarily. But we could reduce the risk greatly if we implement that "well known directories" suggestion I made earlier, instead of copying/moving/symlinking from the entire directory tree.

**Comment by tastytea** [comment]
You mean deploying into the same paths as most Linux distributions? Seems good to me.

**Comment by TheAssassin** [comment]
> You mean deploying into the same paths as most Linux distributions?

More like, only look in there for existing translation files, and create symlinks for them automagically.

**Comment by azubieta** [comment]
The PRs above implements:
> only look in there for existing translation files, and create symlinks for them automagically

**Comment by TheAssassin** [comment]
No, it does not, unfortunately. It doesn't look into said "well known directories", but traverses the entire AppDir.

**Comment by azubieta** [comment]
@TheAssassin sadly, there no a list of "well known directories" that we (or app developers) can use. So in order to be 100% sure that everything is in that dir we have to traverse the whole AppDir.

**Comment by TheAssassin** [comment]
We don't need to be 100% sure about anything. We're always making assumptions about the location of files, especially in this tool. And since we rely on the file extension, I'd rather _not_ create symlinks for files that might turn out not to be a translation file at all.

Just like in linuxdeployqt, I'd rather introduce a list of directories where translations might be located, and extend that on user request.

**Comment by azubieta** [comment]
In case we include a file that is not a translation it will be harmless. Translations are requested by their file names. Therefore this file will never be l loaded.

Also, one of the design principles of linuxdeploy is that the app developer should modify the least possible of the existent code to make an AppImage of it.

**Comment by azubieta** [comment]
@tastytea would you mind trying this version of linuxdeploy-plugin-qt
https://artifacts.assassinate-you.net/artifactory/linuxdeploy-plugin-qt/travis-138/linuxdeploy-plugin-qt-x86_64.AppImage

**Comment by TheAssassin** [comment]
@azubieta well, my idea was to use an environment variable to specify additional translation directories... Well, I guess traversing the AppDir doesn't increase the runtime significantly either, if we run it only if the translation stuff is being deployed. Okay, convinced.

**Comment by tastytea** [comment]
@azubieta That version worked fine. It copied the files from `usr/share/qt5/translations/` to `usr/translations/`.

**Comment by azubieta** [comment]
Closing as fixed. Feel free to reopen if something else comes up.
Thanks @tastytea
