### ISSUE TITLE
[Feature Request] Create static builds

### ISSUE THREAD

**Issue by qurious-pixel** [linuxdeploy/linuxdeploy-plugin-qt#167]
Create static builds. 

Was using `linuxdeploy-static` and did not know it was failing on the plugin.

Create a static build like linuxdeploy.

https://github.com/qurious-pixel/linuxdeploy-plugin-qt/tree/static-build

![image](https://github.com/linuxdeploy/linuxdeploy-plugin-qt/assets/62252937/a30c18d5-8649-441c-8af0-34a9036747d7)

**Comment by TheAssassin** [comment]
Your link makes no sense and your description is anything but exhaustive. You need to fill in more information. Feel free to reopen once you properly described your feature request.

**Comment by TheAssassin** [comment]
Is it the plugin binary itself that causes problems? Or some tool we bundle?

**Comment by qurious-pixel** [comment]
The plugin binary. once I built it with the code from linuxdeploy, everything succeeded (also using linuxdeploy-static).

**Comment by TheAssassin** [comment]
Since you seem to have got it to work, would you send a pull request, please? It's probably a good idea to build the plugin statically, too.
