### ISSUE TITLE
Icons from theme are not displayed in QtWidgets Application

### ISSUE THREAD

**Issue by tastytea** [linuxdeploy/linuxdeploy-plugin-qt#17]
I have a program which I package as a dpkg and as an AppImage, from the same source. The binary from the dpkg shows icons in the toolbar, the AppImage does not. I use icon names specified in the Icon Naming Specification, like `QIcon::fromTheme("list-add")`. I do not modify any environment variables for the AppImage.

In Ubuntu 18.04 no icons are shown, in Gentoo there are icons but not from the system theme.

AppImage: https://schlomp.space/attachments/15cba25f-e5a0-4c14-b08b-df35f8a4672e

.ui-file where I specify the icons: https://schlomp.space/tastytea/whyblocked/src/branch/master/src/whyblocked.ui#L141

The generated code looks like this:
```C++
QIcon icon1;
iconThemeName = QStringLiteral("list-add");
if (QIcon::hasThemeIcon(iconThemeName)) {
    icon1 = QIcon::fromTheme(iconThemeName);
} else {
    icon1.addFile(QStringLiteral("."), QSize(), QIcon::Normal, QIcon::Off);
}
action_add->setIcon(icon1);
```

Edit: Icons are shown in Fedora 28, no icons in Elementary 5.

**Comment by tastytea** [comment]
I built the AppImage in a debian stretch docker container via drone, this is the recipe: https://schlomp.space/tastytea/whyblocked/src/branch/master/.drone.yml

**Comment by tastytea** [comment]
I have the same problem with the QtWidgetsApplication in [linuxdeploy/linuxdeploy-plugin-qt-examples](https://github.com/linuxdeploy/linuxdeploy-plugin-qt-examples).

**Comment by azubieta** [comment]
An AppImage should include all its dependencies. Not only shared libraries but also other resources such as icons. There is no warranty that the icons that you use will be in every Linux system, therefore, you must also embed them.

Two options came to my mind to achieve it:
 1. Embed the whole icon theme or a portion of it (but it must remain a valid [icon theme](https://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html)). Create a script to properly export the XDG_DATA_DIR environment variable and execute your binary.
 2. Just copy the icons and modify your application to properly load them as a fallback.

Still, we must find out why icons from theme are not being loaded properly.

**Comment by azubieta** [comment]
After a lot of testing, I found that `platformthemes` plugins are responsible for several things see (https://github.com/qt/qtbase/blob/c5307203f5c0b0e588cc93e70764c090dd4c2ce0/src/gui/kernel/qplatformtheme.h) including resolution of icons the default system theme.

Therefore if you want that your app looks good on every desktop environment you will have to include a platformtheme plugin for each. Gathering ALL existent and future plugins is just impossible. I would recommend you to modify your application with as mentioned above.

I'll also update the QtWidgetsApplication in order to work properly.

**Comment by azubieta** [comment]
Now the QtWidgetsApplication example updated with a proper implementation of how to deal with icons.
See https://github.com/linuxdeploy/linuxdeploy-plugin-qt-examples/blob/c1210ecadf76bdcbe626624c441bc5a99101eb7e/QtWidgetsApplication/mainwindow.cpp#L11

**Comment by azubieta** [comment]
If your application requires additional plugins you can always use the environment variable `EXTRA_QT_PLUGINS`. This way:

`$EXTRA_QT_PLUGINS=pluginA;pluginB;`
