### ISSUE TITLE
GTK3 integration does not work.

### ISSUE THREAD

**Issue by AnnaLena77** [linuxdeploy/linuxdeploy-plugin-qt#172]
Hi, 

I am trying to deploy a Qt application (6.5.0). It works so far with the qt plugin. Unfortunately the display of the AppImage is horrible, because gtk3 is not used.

I tried the following before deployment:
export QT_QPA_PLATFORMTHEME=gtk3
export QT_STYLE_OVERRIDE=gtk

After the deploy process, the libqgtk3.so plugin is apparently missing in AppDir/usr/plugins/platformthemes (in qt: 6.5.0/plugins/platformthemes/libqgtk3.so). When I add it manually and start the deploy, everything works perfectly on my initial system and gtk3 is applied. 
However, this then does not work on other systems on which I want to use the AppImage, as it has not been inserted properly. An error occurs regarding the library libgio-2.0, which causes differences on the systems.

I have tried to use the gtk plugin (https://github.com/linuxdeploy/linuxdeploy-plugin-gtk) in addition, but the qt plugin and the gtk plugin seem to overwrite each other. 

Is there a way to properly integrate gtk3 (libqgtk3.so)?

Edit1: I tried to use only the plugin with “--extra-plugin=/path/to/libqgtk3.so”. This is not inserted and does not appear in the output.

**Comment by TheAssassin** [comment]
Neither of these environment variables is interpreted by this plugin. I'm not sure where you got those from, but they're runtime variables, i.e., they need to be set during runtime.

The plugin generates a hook script that, if needed, sets `export QT_QPA_PLATFORMTHEME=gtk<version>`, but only if the library was deployed.

The gtk plugin is not needed and should not be used in combination with this plugin.

To deploy the platform themes (which is an experimental feature, often they're not needed), please try and `export DEPLOY_PLATFORM_THEMES=true` before running linuxdeploy.

To ease debugging (i.e., avoid forcing me to reverse engineer the code depending on the few details you provide), please always provide a complete(!) log.

**Comment by AnnaLena77** [comment]
export DEPLOY_PLATFORM_THEMES=true
Is the solution for me!

Now all platformthemes are available in my AppDir after using linuxdeploy. Thank you very much!
