### ISSUE TITLE
Missing tailing "/" ,  target is a file instead of directory

### ISSUE THREAD

**Issue by KjellMorgenstern** [linuxdeploy/linuxdeploy-plugin-qt#184]
When building an AppImage, instead of a 'imageformats' directory I now have a file, with the same size as the libqgif.so.
The same seems to happen for other plugin directories. Instead of directories, there are now files.

```
drwxr-xr-x 2 kjell kjell    4096 Aug  3 22:49 iconengines
-rwxr-xr-x 1 kjell kjell   48440 Aug  3 22:49 imageformats
-rwxr-xr-x 1 kjell kjell   40920 Aug  3 22:49 platforminputcontexts
drwxr-xr-x 2 kjell kjell    4096 Aug  3 22:49 platforms
drwxr-xr-x 2 kjell kjell    4096 Aug  3 22:49 platformthemes
-rwxr-xr-x 1 kjell kjell  137920 Aug  3 22:49 printsupport
-rwxr-xr-x 1 kjell kjell 1495664 Aug  3 22:49 sqldrivers
-rwxr-xr-x 1 kjell kjell  113216 Aug  3 22:49 tls
drwxr-xr-x 2 kjell kjell    4096 Aug  3 22:49 xcbglintegrations
```

This started to happen with the continuous linux-deplot-qt release yesterday, about the same time as some changes to handling plugins were commited.

```
-- Running input plugin: qt --
[qt/stdout] Using qmake: /build/dependencies/qt/6.5.3/gcc_64/bin/qmake
[qt/stderr] linuxdeploy-plugin-qt version 1-alpha (git commit ID 0a29e02), GitHub actions build 174 built on 2024-08-03 00:58:52 UTC
```

`[qt/stdout] Deploying shared library /build/dependencies/qt/6.5.3/gcc_64/plugins/imageformats/libqgif.so (destination: AppDir/usr/plugins/imageformats)`

Note the missing trailing "/" after imageformats

**Comment by TheAssassin** [comment]
Is this happening with the latest continuous build?

**Comment by KjellMorgenstern** [comment]
Yes, with git commit ID 0a29e02

**Comment by KjellMorgenstern** [comment]
Maybe this line needs a "/" behind the pluginName? if (!appDir.deployLibrary(*i, appDir.path() / "usr/plugins" / pluginName))

**Comment by TheAssassin** [comment]
It probably does. Must be related to #175. Would you like to send a PR?
