### ISSUE TITLE
Setting QMAKE doesn't run correct qmlimportscanner - "could not find a Qt installation"

### ISSUE THREAD

**Issue by wrosecrans** [linuxdeploy/linuxdeploy-plugin-qt#26]
The Readme says you can specify a QMAKE environment variable to point at a specific Qt install.  This works well with a local install like

`export QMAKE=/home/will/Qt-5.12/5.12.0/gcc_64/bin/qmake`

And linuxdeploy-x86_64.AppImage with --plugin qt will correctly grab Qt plugin dependencies from that install directory.  But then it starts looking for QML stuff, and it sets the right import path, but invokes the system global qmlimportscanner:

```

[qt/stdout] -- Deploying module: qml -- 
[qt/stdout] QML imports search path:   /home/will/Qt-5.12/5.12.0/gcc_64/qml
[qt/stdout] QML sources search path:   /tmp/output
[qt/stdout] Calling: /usr/bin/qmlimportscanner  -rootPath  /tmp/output  -importPath  /home/will/Qt-5.12/5.12.0/gcc_64/qml  
[qt/stdout] ERROR: qmlimportscanner: could not find a Qt installation of ''
[qt/stdout]  
ERROR: Failed to run plugin: qt (exit code: 1) 

```

Since the system global qmlimportscanner doesn't know about the local install, it gives the `qmlimportscanner: could not find a Qt installation of ''` error.  Invoking the qmlimportscanner from the same directory as qmake seems to work fine.  i.e.  $(dirname $QMAKE)/qmlimportscanner

Is there any way to work around this?

**Comment by TheAssassin** [comment]
@azubieta any ideas?

**Comment by bugwelle** [comment]
Same for me. Had to prepend `Qt/<version>/bin` to my `$PATH` so that `qmlimportscanner` does not reference the system's version.

```sh
export PATH=$HOME/Qt/5.13.0/gcc_64/bin:$PATH
qmake --version # should print 5.13
export QMAKE=$(which qmake)
export QML_SOURCES_PATHS=$HOME/Project/src/ui
mkdir build && cd $_
qmake ..
make -j4
make install INSTALL_ROOT=AppDir
./linuxdeploy-x86_64.AppImage --appdir AppDir --plugin qt --output appimage
# etc.
```

**Comment by azubieta** [comment]
@wrosecrans @bugwelle mind to try [this build](https://artifacts.assassinate-you.net/artifactory/linuxdeploy-plugin-qt/travis-176/linuxdeploy-plugin-qt-x86_64.AppImage)

Basically the `QT_INSTALL_BINS` path was prepended to path so when the qml module looks for it it should be found before the system one.

**Comment by bugwelle** [comment]
Thanks! I didn't have time to test it, yet. Will try it on the weekend :)

**Comment by TheAssassin** [comment]
Let us know about your results so we can close that issue then.

**Comment by bugwelle** [comment]
Tested the new version and it works like a charm! Thanks :smiley: 
(the old one is still failing so it's not due to changes on my system :) )

**Comment by TheAssassin** [comment]
Perfect. Great idea to also re-test the old version. Closing as resolved. Thanks @azubieta.
