### ISSUE TITLE
Set Qt env vars (e.g., for GTK2 platform themes)

### ISSUE THREAD

**Issue by TheAssassin** [linuxdeploy/linuxdeploy-plugin-qt#33]
Should be set accordingly once https://github.com/linuxdeploy/linuxdeploy/issues/81 is implemented.

**Comment by TheAssassin** [comment]
@probonopd now that the feature has been implemented in linuxdeploy, we could realize this. How to detect when we need to set that environment variable?

**Comment by probonopd** [comment]
Scribus is currently using:

```
case "${XDG_CURRENT_DESKTOP}" in
    *GNOME*|*gnome*)
        export QT_QPA_PLATFORMTHEME=gtk2
esac
```

I think we also need to consider Xfce and some others.

**Comment by TheAssassin** [comment]
Is there any documentation on the effect of setting this variable? I can't spot a difference really on my computer...

**Comment by TheAssassin** [comment]
Do we even ship the required style plugins? Is that the segfault-producing thing you once suggested to include in AppImageLauncher that we removed for causing segfaults?

https://www.linuxuprising.com/2018/05/get-qt5-apps-to-use-native-gtk-style-in.html

**Comment by probonopd** [comment]
I think we are not shipping those yet. One needs to compile them and deploy them (but not their dependencies, since we want to use the native Gtk of the target system and just let the plugin fail in cause they are not there.)

**Comment by probonopd** [comment]
Setting those variables makes a big difference. If you want to try it for yourself, download the continuous [Scribus AppImage](https://gitlab.com/scribus/scribus/-/jobs) and run it on Gnome. Looks pretty native, right? Then extract it and comment out that section in the AppRun, and run again. Looks pretty ugly then...

**Comment by TheAssassin** [comment]
We can set the variables. It's the up to the user to include those style plugins. I don't think *we* have to automate that.

Do you want to ask Stephan Binner to include those plugins in his Qt PPAs?

**Comment by probonopd** [comment]
I think (not 100% sure though) that at some point the upstream Qt project separated the plugins out from the main project into its own subproject. I'd suspect that Stephan Binner wants to stay close to upstream. Shall we ask upstream to re-include them? (Imho Qt on Linux has been broken ever since they removed them from the default installation...)

**Comment by TheAssassin** [comment]
So you once suggested the following code for inclusion in the obsolete `AppRun.c`:

```
case "${XDG_CURRENT_DESKTOP}" in
    *GNOME*|*gnome*|*XFCE*|)
        export QT_QPA_PLATFORMTHEME=gtk2
esac
```

The code is broken for multiple reasons:
* section catches empty values of `XDG_CURRENT_DESKTOP`, overwrites the env var nevertheless
* broken syntax: missing `;;`

The Scribus code you posted is also broken. I've corrected it just like the code in the original issue over at AppImageKit, so people won't pick up broken code by accident.

I'm including the following now:

```
case "${XDG_CURRENT_DESKTOP}" in
    *GNOME*|*gnome*|*XFCE*)
        export QT_QPA_PLATFORMTHEME=gtk2
        ;;
esac

**Comment by probonopd** [comment]
Which is "the obsolete" `AppRun.c`? I don't consider it as "obsolete", as I am still actively using it in some scenarios (i.e., where I can't use linuxdeploy*).
