### ISSUE TITLE
Difference between this plugin and linuxdeployqt

### ISSUE THREAD

**Issue by bugwelle** [linuxdeploy/linuxdeploy-plugin-qt#36]
Hi,

I was just wondering: What's the difference between linuxdeploy (+ this plugin) and [linuxdeployqt](https://github.com/probonopd/linuxdeployqt/)?

Their names are quite similar but their usage is quite different. I couldn't find an answer to this, yet.
A short note in `README.md` would be helpful :)

Regards,
Andre

**Comment by bugwelle** [comment]
@probonopd could you bring some light to this issue? :)

**Comment by probonopd** [comment]
linuxdeployqt is older, and is based on macdeployqt (a part of Qt). It focuses on being simple, and has no plugins and little configurability. linuxdeploy is a complete rewrite, has a plugin architecture and more configurability. It is faster and more powerful, but also more complex.

**Comment by TheAssassin** [comment]
linuxdeploy-plugin-qt is first and foremost a standalone deployment system for apps' Qt dependencies, such as Qt plugin libraries, QML files etc. It is designed to work together with linuxdeploy, which does the heavy lifting of deploying the app itself and its direct library dependencies along with desktop files, icons and other things an AppImage/AppDir generally needs, the plugin amends the things linuxdeploy already deployed then.

linuxdeploy with the Qt plugin are faster, provide more features and overall are easier to use, they provide a meaningful logging system and make debugging easy.

**Comment by TheAssassin** [comment]
Has your question been answered satisfyingly, @bugwelle?

**Comment by bugwelle** [comment]
My bad, sorry. Forgot to answer.

Yes, my question has been answered. But it may be worth to add a note about this in this project's README because I'm sure that I'm not the only one to be confused. 😃  
Furthermore, is linuxdeploy-plugin-qt the preferred way to bundle Qt applications? Because my thoughts when finding this plugin were that it replaces linuxdeployqt.

Thanks.

**Comment by TheAssassin** [comment]
See https://github.com/AppImage/docs.appimage.org/commit/823992ffde2112f87f3ad2184b722c4ad2d09ad7#diff-af4bfff6f66936537f91123ab9a6be61L108 and https://github.com/AppImage/docs.appimage.org/commit/8ffceaf96774fe17fff98c7b67d247a7099f354c.

**Comment by bugwelle** [comment]
Oh, didn't see that. Thank you 👍

**Comment by TheAssassin** [comment]
I may not call it the successor yet, but if you ask me... go with linuxdeploy, much more modern, faster, well tested.

**Comment by bugwelle** [comment]
I've been using linuxdeploy-plugin-qt for more than a month now for nightly versions of MediaElch (switched from linuxdeployqt).

```sh
export QML_SOURCES_PATHS="${PROJECT_DIR}/src/ui"
# Run linuxdeploy with following settings:
# - use qt plugin       => so that Qt libraries are bundled correctly
# - use checkrt plugin  => we use C++14 which requires libstdc++-6 which is not available on older systems
#                          this plugin bundled these newer libraries as well
# - use appimage plugin => create an appimage file (essentially just bundles the appdir)
"./linuxdeploy-x86_64.AppImage" --appdir appdir                    \
	--desktop-file appdir/usr/share/applications/MediaElch.desktop \
	--plugin checkrt                                               \
	--plugin qt                                                    \
	--output appimage

```
https://github.com/Komet/MediaElch/blob/89168251a53613873ffce53daf040e70384239d5/travis-ci/package.sh#L155-L173

Didn't hear complaints from users, yet. So I assume it's working just fine 😅

**Comment by TheAssassin** [comment]
Cool. Does the checkrt plugin work well for you? It's pretty... alpha...

**Comment by bugwelle** [comment]
Kind of... Not worse than before. But because of gstreamer issues, etc., I wouldn't call MediaElch's AppImage stable.
I'll have to check on that again (maybe on the weekend). If I haven't screwed up anything then the AppImage should work on Ubuntu 14.04 and later. :)

**Comment by TheAssassin** [comment]
Oh, that's great to hear, would you want to collaborate on fixing the GStreamer issues? We know there's potential for linuxdeploy plugins that shall properly bundle GStreamer, and I'd like to see what you're doing to bundle them and how we could generalize that and make it another plugin.

Please consider joining #appimage on Freenode, where we could talk about this. Meanwhile, please see https://github.com/linuxdeploy/linuxdeploy/issues/80 for more information.

Oh, by the way, I've listed your project in the READMEs of linuxdeploy, linuxdeploy-plugin-checkrt and awesome-linuxdeploy as a user of our tools. Please feel free to proofread and improve the texts.

By the way, [your script](https://github.com/Komet/MediaElch/blob/25fe92d405c8178968f4349c4b3638d7fa34e850/scripts/packaging/package.sh#L134) still says linuxdeployqt and also has a few workarounds that are no longer needed. I might consider sending a PR, but so far it looks good.

**Comment by bugwelle** [comment]
> Oh, that's great to hear, would you want to collaborate on fixing the GStreamer issues?

Sure. But to be honest: I don't even know what part of MediaElch requires gstreamer (probably ffmpeg or mediainfo?). So there's a lot of new information in areas I've never touched. :)

> Oh, by the way, I've listed your project in the READMEs of linuxdeploy, linuxdeploy-plugin-checkrt and awesome-linuxdeploy as a user of our tools. Please feel free to proofread and improve the texts.

Thanks. Now I've got no choice but to make MediaElch's AppImage stable :P
I won't have time for the next 1-2 weeks. I'll look into your points after that. :-)

> By the way, your script still says linuxdeployqt and also has a few workarounds that are no longer needed. I might consider sending a PR, but so far it looks good.

Oh, didn't notice that. Thanks. 😄
