### ISSUE TITLE
xcb not necessarily bundled for Qt >= 5.12.1

### ISSUE THREAD

**Issue by haampie** [linuxdeploy/linuxdeploy-plugin-qt#40]
In Qt 5.12.1 and later, the xcb plugin is not necessarily provided:

https://code.qt.io/cgit/qt/qtbase.git/tree/dist/changes-5.12.1?h=5.12.1

> Removed xkbcommon from bundled sources. This library is present on all supported platforms. The minimal required version now is  0.5.0.

I think linuxdeploy-plugin-qt now only works when qt is compiled with `-qt-xcb`. Maybe make this plugin optional? We should only ship it if it's there.

---

Sorry, this issue is not very detailed, but recently I've switched to using https://github.com/darkmattercoder/qt-build which for some reason does not compile with `-qt-xcb`. I have to figure out why.

**Comment by TheAssassin** [comment]
Why did you close this?

**Comment by haampie** [comment]
It's closed because I thought it did not make sense to compile Qt without `-qt-xcb`. I'm still figuring out what this `qt-build` repo exactly does.
