### ISSUE TITLE
Failed build

### ISSUE THREAD

**Issue by haampie** [linuxdeploy/linuxdeploy-plugin-qt#42]
There is no current release for the x86_64 architecture.

**Comment by haampie** [comment]
Could you retrigger CI? I've tried it on my clone and now it seems to work.

**Comment by alexzk1** [comment]
yeh, this link is broken:
https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage

**Comment by haampie** [comment]
Maybe it's an idea to keep at least one stable, tagged version? This is clearly the downside of having just one version.

**Comment by TheAssassin** [comment]
Triggered a rebuild. Stupid Travis...

> Maybe it's an idea to keep at least one stable, tagged version? This is clearly the downside of having just one version.

I tend to just go for my own CI infra again. That way I can implement such features more easily. Travis is constantly annoying.

**Comment by haampie** [comment]
Thanks!

**Comment by TheAssassin** [comment]
Build available again. Thanks for notifying! I'm going to think about how to avoid these situations in the future.
