### ISSUE TITLE
Output final file name

### ISSUE THREAD

**Issue by alexzk1** [linuxdeploy/linuxdeploy-plugin-qt#44]
It makes output name based on "Name" field of .desktop file. However it is supposed to be long reading string for humans and may contain not allowed characters on FS.
Can you add option to explicit name output binary ?

**Comment by alexzk1** [comment]
Upd: sorry I could put issue in wrong repo.

**Comment by TheAssassin** [comment]
JFYI, I could've/would've transferred the issue between the repositories, as they're in the same organization.
