### ISSUE TITLE
Some plugins are not deployed

### ISSUE THREAD

**Issue by haampie** [linuxdeploy/linuxdeploy-plugin-qt#46]
When deploying a Qt 3d application, some plugins were not deployed automatically. Specifically `plugins/geometryloaders/{libdefaultgeometryloader,libgltfgeometryloader}.so`.

And while I'm at it, it seems that there is a plugin `gamepads/libevdevgamepad.so` whereas the module name in `qt-modules.h` is `gamepad`.

Further `plugins/sceneparsers` seems to be ignored as well.

I could open a PR to fix all this. The question is mostly whether these plugins are dependent on a specific Qt version, things should not fail if the plugins do not exist on older versions of Qt or whenever they have different names (e.g. gamepad?).

**Comment by haampie** [comment]
I'm confused, the plugins in https://github.com/linuxdeploy/linuxdeploy-plugin-qt/blob/master/src/main.cpp#L577-L624 all have some special logic, but what about plugins that do not match? There are more plugins listed in qt-modules.h. In that case, shoudn't there be a generic fallback that simply copies a plugin folder over to the appdir?

**Comment by TheAssassin** [comment]
You could just create a new method `deploy3dPlugins()` that copies over those files conditionally (following some best effort logic, i.e., copying whatever is there but not failing when something is missing.

**Comment by haampie** [comment]
How about this fallback idea? Just make it possible for the user to copy over a plugin by folder without any specific logic?

**Comment by TheAssassin** [comment]
I don't see how this is supposed to be realized in an easy enough way by changing `qt-modules.h`'s format, adding another deployment method seems easy enough to me.

Or is the user you describe the user of the CLI who wants to specify additional modules to be deployed? In that case, `EXTRA_QT_PLUGINS` should do.

**Comment by haampie** [comment]
Closing this because of the previous two prs.
