### ISSUE TITLE
PlatformPluginsDeployer and XcbglIntegrationPluginsDeployer not exclusive

### ISSUE THREAD

**Issue by haampie** [linuxdeploy/linuxdeploy-plugin-qt#51]
If only `gui` is detected as a plugin, the xcbgl integration is not deployed, because at the moment the factory will only build a single deployer. Maybe we can just merge those two deployers, but I have to double check it makes total sense.

**Comment by haampie** [comment]
So, quick research: the `opengl` module has been deprecated since Qt 5.4.0; the previous version aka Qt 5.3 was EOL 10.12.2016; this is (unfortunately) still after the oldest LTS version of Ubuntu. So maybe we should not completely drop the `opengl` check.

At any rate, the safest thing is just to deploy both platformplugins and xcbgl integration plugins when `gui` is detected. I'll just make a fix that does that.

**Comment by TheAssassin** [comment]
Should be fixed as of merging #52. I assume we can close this one?
