### ISSUE TITLE
How to set XDG_DATA_DIRS ?

### ISSUE THREAD

**Issue by abcfy2** [linuxdeploy/linuxdeploy-plugin-qt#53]
Qt search theme path from `XDG_DATA_DIRS`, see: https://doc.qt.io/qt-5/qicon.html#themeSearchPaths

But how could I set `XDG_DATA_DIRS` in AppImage?

**Comment by abcfy2** [comment]
I think maybe it's useful to add `XDG_DATA_DIRS` to `squashfs-root/apprun-hooks/linuxdeploy-plugin-qt-hook.sh`:

```bash
# generated by linuxdeploy-plugin-qt

# try to make Qt apps more "native looking", if possible
# see also https://github.com/AppImage/AppImageKit/issues/977#issue-462374883
# and https://github.com/AppImage/AppImageKit/issues/977#issue-462374883
case "${XDG_CURRENT_DESKTOP}" in
    *GNOME*|*gnome*|*XFCE*)
        export QT_QPA_PLATFORMTHEME=gtk2
        ;;
esac

export XDG_DATA_DIRS="${squashfs_root_path}/usr/share:${XDG_DATA_DIRS}:/usr/share:/usr/local/share"
```

**Comment by TheAssassin** [comment]
This likely has some side effects, I'm not sure if this is a good idea. Why would you need this variable to be set?

Using a second hook seems like an elegant solution.

**Comment by abcfy2** [comment]
I try to make a qt AppImage.

```bash
# From guide: https://docs.appimage.org/packaging-guide/native-binaries.html#qmake
./configure --prefix=/usr
make install INSTALL_ROOT=AppDir
```

And AppImage prefix is not `/usr/`, so qt application cannot find the theme icons, so I have to set `XDG_DATA_DIRS` to set a new theme path.

And second hook seems working.

**Comment by TheAssassin** [comment]
Is it possible to fix some of the paths e.g., using `qt.conf`? That file contains paths *relative to the binary*, and doesn't require any ugly environment hacks that might influence other components as well.

**Comment by abcfy2** [comment]
But I can't find how to set [themeSearchPaths](https://doc.qt.io/qt-5/qicon.html#themeSearchPaths) in `qt.conf`

**Comment by TheAssassin** [comment]
Can't you use https://doc.qt.io/qt-5/qicon.html#setThemeSearchPaths in your code? That won't pollute your environment variables. You can fetch the mounted AppDir location from the environment (`$APPDIR`).

**Comment by abcfy2** [comment]
I just make a AppImage for https://github.com/c0re100/qBittorrent-Enhanced-Edition. So I think I can't modify the source code.

And I think set environment variable is the simplest way without change any codes.
