### ISSUE TITLE
Deploying with GTK2 by default instead of GTK3

### ISSUE THREAD

**Issue by qwertysam** [linuxdeploy/linuxdeploy-plugin-qt#58]
I've been using this tool combined with `linuxdeploy-appimage`, and I was confused for a long time as to why the text and theming of the AppImage was different from my original program. Applications using Qt 5.8+ use Gtk3 by default, and that's what I wanted bundled with my app (made with Qt 5.14). It's great that there's legacy support, but I think this should be documented somewhere so that users can easily find how to switch between the legacy GTK2 and GTK3. To fix this, I added `export DEPLOY_PLATFORM_THEMES=1` to my build script, which results in GTK3 being used instead of GTK2, via this line of code:

https://github.com/linuxdeploy/linuxdeploy-plugin-qt/blob/8f37917e428dd1c0734457074d211a432a09410f/src/deployers/PlatformPluginsDeployer.cpp#L41

Note that running `linuxdeploy` with the `qt` plugin would actually still deploy `libqgtk3.so`, and would log
```
[qt/stdout] Trying to deploy Gtk 2 platform theme and/or style 
[qt/stdout] Could not find libqgtk2.so on system, skipping deployment 
[qt/stdout] Could not find libqgtk2style.so on system, skipping deployment 
```
but somehow it still deployed and ran with the `libqgtk2.so` library.

I also noted that the generated file `AppDir/apprun-hooks/linuxdeploy-plugin-qt-hooks.sh` is still exporting `QT_QPA_PLATFORMTHEME=gtk2`, but seems to not have an effect on the running application.

**Comment by realnc** [comment]
Fixed by 84797c0e05e6904f6ceb90312be277b360074b08 and d245b4dc0f7687e8c3a7b58bebf03136e13101a7.
