### ISSUE TITLE
linuxdeploy + linuxdeploy-plugin-qt does not deploy printsupport plugin module

### ISSUE THREAD

**Issue by AntonioBL** [linuxdeploy/linuxdeploy-plugin-qt#59]
When building MuseScore with linuxdeploy + linuxdeploy-plugin-qt, linuxdeploy finds some Qt modules, see https://travis-ci.org/musescore/MuseScore/jobs/634744261#L3770
but it does not install all of them. For example, it does not install printsupport module (i.e. folder plugins/printsupport and its content) and this causes a printing bug in MuseScore AppImage, see https://musescore.org/en/node/297719
In the log, nothing is printed, see https://travis-ci.org/musescore/MuseScore/jobs/634744261#L3971 even when using `DEBUG=1` before launching linuxdeploy.

**Comment by TheAssassin** [comment]
Good catch. We should really add support.

Do you think just copying the files is sufficient? Do we need any external dependencies? If not, it'll be very easy to add support for it to this plugin.

**Comment by TheAssassin** [comment]
Actually printsupport is listed in the plugins database, so it should be deployed. I wonder why it doesn't work for you...

**Comment by TheAssassin** [comment]
I see... ld-p-qt has indeed recognized the dependency (see https://travis-ci.org/musescore/MuseScore/jobs/634744261#L3971), but it hasn't deployed any additional files. We need a custom deployer copying the contents of the `printsupport` directory.

**Comment by TheAssassin** [comment]
@AntonioBL I sent a PR, binaries are built right now, please test those with your project. If they work, we can merge the PR.
