### ISSUE TITLE
EXTRA_QT_PLUGINS does not work

### ISSUE THREAD

**Issue by realnc** [linuxdeploy/linuxdeploy-plugin-qt#61]
When I run:

    EXTRA_QT_PLUGINS=platformthemes \
    QMAKE=~/opt/qt-5.14.1/bin/qmake \
    linuxdeploy-x86_64.AppImage --appdir=AppDir --plugin qt

the generated AppDir does not contain the platform plugins. I have to manually copy the `plugins/platformthemes` directory from the Qt installation to the AppDir.

**Comment by TheAssassin** [comment]
Please share a log of running linuxdeploy. The command looks correct as far as I can see. I'd like to see what's going on.

**Comment by TheAssassin** [comment]
The platform themes are not a Qt plugin. I can deploy e.g., `printsupport` or `xml` just fine. See https://github.com/linuxdeploy/linuxdeploy-plugin-qt/blob/master/src/qt-modules.h for a list of Qt modules that can be specified this way.

The platform themes are deployed for the `gui` module. Try using `EXTRA_QT_PLUGINS=gui` and it should work as intended. (See https://github.com/linuxdeploy/linuxdeploy-plugin-qt/blob/master/src/deployers/PluginsDeployerFactory.cpp for more information).

OTOH, it's quite weird that you have to specify them manually. As soon as `libQt5Gui` is linked, the `gui` module should be deployed automatically. Therefore please post a log.

**Comment by realnc** [comment]
This is the log:

https://pastebin.com/raw/KeaUxT9d

And this is the Qt installation (64-bit, built from source.) It should be relocatable, according to the docs:

 (19MB)
http://83.212.109.87/~realnc/tmp/qt-5.14.1.tar.xz

**Comment by realnc** [comment]
Submitted https://github.com/linuxdeploy/linuxdeploy-plugin-qt/pull/62 for this.

**Comment by TheAssassin** [comment]
I see. The problem here then wasn't that `EXTRA_QT_PLUGINS` didn't work, but it didn't deploy Gtk+3. Thanks for fixing.

IMO there's another issue that we should take care of. It's hard to guess what to specify for `EXTRA_QT_PLUGINS`. We could build a simple CLI option that lists the available options.

**Comment by realnc** [comment]
> IMO there's another issue that we should take care of. It's hard to guess what to specify for `EXTRA_QT_PLUGINS`. We could build a simple CLI option that lists the available modules.

Well, right now I need to first make the appimage plugin work at all:

```
[appimage/stdout] W - nikos.chantziaras.qtads.appdata.xml:nikos.chantziaras.qtads
[appimage/stdout]     Component id belongs to a desktop-application, but does not resemble the .desktop file name: "nikos.chantziaras.qtads"
[appimage/stdout] 
[appimage/stdout] E - nikos.chantziaras.qtads.appdata.xml:nikos.chantziaras.qtads
[appimage/stdout]     Invalid property for 'url' tag: "contact"
[appimage/stdout] 
[appimage/stdout] E - nikos.chantziaras.qtads.appdata.xml:nikos.chantziaras.qtads
[appimage/stdout]     Component metadata refers to a non-existing .desktop file.
[appimage/stdout] 
[appimage/stdout] W - nikos.chantziaras.qtads.appdata.xml:nikos.chantziaras.qtads
[appimage/stdout]     Found invalid tag: 'launchable'. Non-standard tags must be prefixed with "x-".
[appimage/stdout] 
[appimage/stdout] Validation failed.
[appimage/stderr] Failed to validate AppStream information with appstreamcli
ERROR: Failed to run plugin: appimage
```

From what I can tell, all of these errors are wrong and there is no way to not have it validate :-/

**Comment by TheAssassin** [comment]
This report is generated by `appstream-cli`. This tool is provided by the AppStream folks. Those errors are therefore not "wrong". But this doesn't seem like the right place to discuss the problem. Please refer to https://github.com/AppImage/AppImageKit/issues/1011.
