### ISSUE TITLE
QT_QPA_PLATFORMTHEME=xdgdesktopportal forces Qt-filedialog to stop working

### ISSUE THREAD

**Issue by Arne-W** [linuxdeploy/linuxdeploy-plugin-qt#66]
I am building an Qt AppImage with the latest linuxdeploy tools. Everything is working fine except the Qt-filedialog which does not show up as long as the `QT_QPA_PLATFORMTHEME=xdgdesktopportal` is set. Changing the linuxdeploy-plugin-qt-hook.sh script to not set this variable fixed this behaviour as well as setting `QT_QPA_PLATFORMTHEME=qt5ct`

Using ubuntu 16.04 for building the AppImage and Kubuntu 18.04 for its execution.

Changing the script to:
```
case "${XDG_CURRENT_DESKTOP}" in
    *KDE*|*kde*)
        export QT_QPA_PLATFORMTHEME=qt5ct
        ;;
    *GNOME*|*gnome*|*XFCE*)
        export QT_QPA_PLATFORMTHEME=gtk3
        ;;
    *)
        export QT_QPA_PLATFORMTHEME=xdgdesktopportal
        ;;
esac
```
worked for me.

**Comment by realnc** [comment]
If I do this, then I'm not getting a native file dialog anymore :-/

**Comment by Arne-W** [comment]
@realnc Hmm - does it work if you do not set the `QT_QPA_PLATFORMTHEME` at all? For me that worked too when using KDE.

**Comment by realnc** [comment]
I don't set it to `xdgdesktopportal`, then I don't get native file dialogs.

**Comment by Arne-W** [comment]
What do you mean exactly with native file dialogs? On Kubuntu 18.04 with KDE and Qt5.12 the file dialog opened when calling `QFileDialog()` does not show.

**Comment by realnc** [comment]
I mean that without using the xdgdesktopportal plugin,,I get the fall-back Qt file dialog:

![image](https://user-images.githubusercontent.com/1665903/76167298-44652e80-616e-11ea-85c6-baa5b4996f24.png)

But with the plugin, I get the native KDE file dialog:

![image](https://user-images.githubusercontent.com/1665903/76167333-7e363500-616e-11ea-8dbc-0243a1e8ad20.png)

**Comment by Arne-W** [comment]
What? My `QFileDialog()` always looks like the first one you posted - regardless of packed into the AppImage or not! Never seen a dialog like the second one when using Qt.

**Comment by realnc** [comment]
If you build your Qt application using the Kubuntu provided Qt libraries, you get a native UI for everything (remember that KDE apps are Qt apps.) But when there's a version mismatch between the Qt build KDE is using the build your app is using, then you don't get a native UI, including file dialogs. The xdgdesktopportal portal can't fix the UI issue, but at least it fixes the file dialog issue.

**Comment by realnc** [comment]
Ah, maybe Kubuntu doesn't ship the xdg-desktop-portal-kde package? I use Gentoo, and it ships it (kde-plasma/xdg-desktop-portal-kde).

**Comment by Arne-W** [comment]
The xdg-desktop-portal-kde package is installed on my system. But I am Building in a docker container on an ubuntu 16.04 with Qt5.12. The deploy tools are extracted and used inside the container. The Qt version in that container does not match the native 16.04 version. I tried to use the native Qt version of that container but the qmlImportscanner did not do its job - so i was not able to test what happens in that case.
Nevertheless getting no file dialog at all is a mess...

**Comment by realnc** [comment]
As a test, can you download this application:

https://github.com/realnc/hugor/releases/tag/v2.2

and see if it exhibits the issue? The application should immediately display a file dialog when you run it.

**Comment by TheAssassin** [comment]
Seems like you all tested this thoroughly. I don't like "fixes" that create more issues either. Thanks folks, I'll have a look at @realnc's PR immediately.

**Comment by Arne-W** [comment]
@realnc Sorry I did not have the time for testing. Nevertheless thank you for the efford and the change.
👍

**Comment by magimaiprakash** [comment]
Hey All,

I am using Linux Mint 19.3 Xfce Edition, I too faced the similar situation, when using AppImageUpdate-x86_64.AppImage, I couldn't get the file chooser dialog box, but when using the complete path of the AppImage as a argument while running AppImageUpdate-x86_64.AppImage in console like so,

` ./AppImageUpdate-x86_64.AppImage /home/tuxmachine/Downloads/AppImageUpdate-x86_64.AppImage`

the progress bar only appears.

**Screenshot**:

![screenshot_1](https://user-images.githubusercontent.com/37093731/78727842-70cdbf80-7953-11ea-8678-40c42bd8b7be.png)

**Comment by TheAssassin** [comment]
@magimaiprakash you should be able to show details when clicking on the arrow. The window looks normal.

@realnc any idea why this would happen on a Gtk2/XFCE desktop?

**Comment by realnc** [comment]
I have no idea what this or how it is related to this bug.

**Comment by TheAssassin** [comment]
It's an AppImageUpdate window. @magimaiprakash is a less experienced user who has reported the problem on IRC, so the description isn't *that* precise.

The issue is that the application crashes on the file dialog, which opens if you launch the application without passing a filename as parameter.
