### ISSUE TITLE
NOOP Code at deployWebEnginePlugins

### ISSUE THREAD

**Issue by azubieta** [linuxdeploy/linuxdeploy-plugin-qt#7]
What's this code block purpose? I think it could be safely removed. 
https://github.com/linuxdeploy/linuxdeploy-plugin-qt/blob/c92f941510ecfd0fedd75ef8b39ce2d824ecbc6c/src/main.cpp#L194

**Comment by TheAssassin** [comment]
That's not a "noop" per definition. It's a comment telling users which application has generated the config file, e.g., for debugging purposes. This has been adopted from linuxdeployqt.

What's your point? Do you want to remove it? I think it makes sense to keep it there.

**Comment by azubieta** [comment]
I think it tries to write into the qt.conf file. And the data it writes it's incomplete and redundant with https://github.com/linuxdeploy/linuxdeploy-plugin-qt/blob/c92f941510ecfd0fedd75ef8b39ce2d824ecbc6c/src/main.cpp#L201

**Comment by TheAssassin** [comment]
It's a separate Qt config file. Why not add a comment there? Let's not waste time about this comment.

**Comment by azubieta** [comment]
It was a misunderstanding. It's a different  "qt.conf" file.
