### ISSUE TITLE
No texttospeech deployment

### ISSUE THREAD

**Issue by julonexus** [linuxdeploy/linuxdeploy-plugin-qt#70]
Hi
I think there is an issue on TextToSpeech module deployment. The module has been detected but no folder are deployed in plugins/. That lead to get the error `No text-to-speech plug-ins were found.` when executing the application.

```
[qt/stdout] Found Qt modules: concurrent core dbus gui network qml quick quickcontrols2 quicktemplates2 svg texttospeech widgets 
...
[qt/stdout] -- Deploying module: texttospeech -- 
[qt/stdout] 
[qt/stdout] -- Deploying module: widgets -- 
```
The script is downloaded from [there](https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage)
You can check the call code [here](https://gitlab.linphone.org/BC/public/linphone-desktop/blob/master/linphone-app/tools/create_appimage.sh#L80)

**Comment by TheAssassin** [comment]
There's no special handling of that plugin as of yet, nobody's taken the time to tinker with the module's dependencies, which ones have to deployed and which ones not, etc.

Do you happen to know what files we have to distribute? It'll be quite easy to add support once we know what to deploy.

**Comment by julonexus** [comment]
From the Qt 5.12.5, this is the folder plugins/texttospeech.
There is the file libqtexttospeech_speechd.so (and libqtexttospeech_speechd.so.debug)

**Comment by TheAssassin** [comment]
On Ubuntu bionic, the file is `plugins/texttospeach/libqttexttospeech_flite.so`. I presume it should be fine to just deploy the directory with whatever it contains.

**Comment by julonexus** [comment]
Or only *.so in this folder? It will be enough generic and keep away from *.so.debug

**Comment by TheAssassin** [comment]
Well, other than space wise, the `.debug` file shouldn't affect the deployment. We cannot really predict whether Qt isn't going to add other companion files there, and then, despite claiming we support the plugin, if it doesn't deploy one file then, it'll be quite hard to debug.

Mind to share the size of your files?

**Comment by julonexus** [comment]
O fource, the .so is about 57.8kB and the .so.debug is around 1.2MB

**Comment by TheAssassin** [comment]
I guess it's reasonable to bundle both then. The `.so`'s dependencies need to be calculated as well, of course, and AppImages are compressed anyway. I'll leave a note in the code that the `.debug` one is likely not needed.

**Comment by julonexus** [comment]
I prefer to not having useless space but it should be enough :)
Thank you for your reactivity :D

**Comment by TheAssassin** [comment]
Let's blacklist these files then, so we actively exclude those instead of actively including only the `.so` stuff.

**Comment by TheAssassin** [comment]
Hadn't added support for a new plugins type in a while, and it turned out that most of them just try to deploy all files as libraries. So I'll just copy that idea for this one, add a little "ignore" for the `.debug` file and we should be fine. At least this is going to error out if there should be non-library files other than the `.debug` stuff, which we ignore deliberately.

**Comment by TheAssassin** [comment]
Fixed, build is on the way. Feel free to reopen if it doesn't work.

**Comment by julonexus** [comment]
Ok thank you very much

**Comment by julonexus** [comment]
There is an issue : the texttospeech is like a file and not a folder type : "shared library (application/x-sharedlib)".
The deployment seems to be fine :
```
[qt/stdout] -- Deploying module: texttospeech -- 
[qt/stdout] Deploying texttospeech plugins 
[qt/stdout] Deploying shared library /usr/lib64/qt5/plugins/texttospeech/libqtexttospeech_speechd.so (destination: WORK/Packages/AppImageDir/AppDir/usr/plugins/texttospeech)
[qt/stdout] Deploying dependencies for ELF file /usr/lib64/qt5/plugins/texttospeech/libqtexttospeech_speechd.so 
[qt/stdout] Deploying shared library /usr/lib64/libspeechd.so.2
```
 but there is this step after:
```
[qt/stdout] Copying file /usr/lib64/qt5/plugins/styles/libqgtk2style.so to WORK/Packages/AppImageDir/AppDir/usr/plugins/styles/libqgtk2style.so 
[qt/stdout] Copying file /usr/lib64/qt5/plugins/texttospeech/libqtexttospeech_speechd.so to WORK/Packages/AppImageDir/AppDir/usr/plugins/texttospeech 
```
The folder is replaced by the library.

**Comment by TheAssassin** [comment]
Oh, darn, I see. You're right. it's a simple fix, just need to suffix the target path with a  `/`.

**Comment by julonexus** [comment]
ha nice, I tried to check your code but I didn't see that ^^
Edit : and I couldn't reopen the issue but it's fine

**Comment by TheAssassin** [comment]
Checked it again in my console, should be really fixed now. Let me know if not. Thanks for testing!

**Comment by julonexus** [comment]
I confirm that it works. Thank you!
