### ISSUE TITLE
Not working any more.

### ISSUE THREAD

**Issue by abcfy2** [linuxdeploy/linuxdeploy-plugin-qt#74]
Here is my build:

https://travis-ci.com/github/c0re100/qBittorrent-Enhanced-Edition/builds/181556476

And

https://travis-ci.com/github/abcfy2/qBittorrent-Enhanced-Edition/builds/181877447

And add `DEBUG=1` cause this error:

```shell
$ DEBUG=1 APPIMAGE_EXTRACT_AND_RUN=1 OUTPUT='qBittorrent-Enhanced-Edition.AppImage' /tmp/linuxdeploy-x86_64.AppImage --appdir="/tmp/qbee/AppDir" --output=appimage --plugin qt
# ...
munmap_chunk(): invalid pointer
```

**Comment by TheAssassin** [comment]
Wrong tracker. Also duplicate issue. See #73.
