### ISSUE TITLE
exclude libOpenGL.so.0*

### ISSUE THREAD

**Issue by okaerin** [linuxdeploy/linuxdeploy-plugin-qt#78]
I reported an issue with the deployment of my Qt application [linuxdeploy/linuxdeploy](https://github.com/linuxdeploy/linuxdeploy/issues/152) . On the IRC channel #appimage i was led to believe that this might be an issue with the plugin. Could it be that the shared library file libOpenGL.so.0* gets mistakenly deployed in an appimage?

**Comment by TheAssassin** [comment]
One issue is enough to track this. linuxdeploy-plugin-qt uses liblinuxdeploy internally anyway.
