### ISSUE TITLE
Qt 6.2.0-beta binaries move qmlimportscanner to libexec

### ISSUE THREAD

**Issue by spiderkeys** [linuxdeploy/linuxdeploy-plugin-qt#93]
Just wanted to give a heads up that qmlimportscanner has been moved to \<QTDIR\>/gcc_64/libexec in the latest release. This can be manually worked around by setting your PATH before running linuxdeploy, but should probably be taken into account by this plugin, much like in this old issue:

https://github.com/linuxdeploy/linuxdeploy-plugin-qt/issues/26

**Comment by bjorn** [comment]
Can be closed since #92 was merged.
