### ISSUE TITLE
How to use linuxdeploy-plugin-qt with a cmake project?

### ISSUE THREAD

**Issue by rsevero** [linuxdeploy/linuxdeploy-plugin-qt#96]
How do I use linuxdeploy-plugin-qt with a cmake project?

When I try to use linuxdeploy-plugin-qt I get the following error message: _[qt/stdout] ERROR: Could not find Qt modules to deploy_

```
$ LD_LIBRARY_PATH=~/Qt-6.2/6.2.0/gcc_64/lib linuxdeploy-x86_64.AppImage --appdir AppDir --plugin qt -e Mapiah -d Mapiah.desktop 
(...)
-- Running input plugin: qt -- 
[qt/stdout] Using qmake: /usr/bin/qmake 
[qt/stdout] 
[qt/stdout] Using Qt version:  5.12.8  ( 5 ) 
[qt/stdout]   libEGL.so.1  libGL.so.1  libGLX.so.0  libGLdispatch.so.0  libQt6Core.so.6  libQt6DBus.so.6  libQt6Gui.so.6  libQt6Widgets.so.6  libX11.so.6  libXau.so.6  libXdmcp.so.6  libbsd.so.0  libc.so.6  libdbus-1.so.3  libdl.so.2  libexpat.so.1  libfontconfig.so.1  libfreetype.so.6  libgcc_s.so.1  libgcrypt.so.20  libglib-2.0.so.0  libgpg-error.so.0  libgthread-2.0.so.0  libicudata.so.56  libicui18n.so.56  libicuuc.so.56  liblz4.so.1  liblzma.so.5  libm.so.6  libpcre.so.3  libpng16.so.16  libpthread.so.0  librt.so.1  libstdc++.so.6  libsystemd.so.0  libuuid.so.1  libxcb.so.1  libxkbcommon.so.0  libz.so.1
[qt/stdout] Found Qt modules:  
[qt/stdout] Extra Qt modules:  
[qt/stdout] ERROR: Could not find Qt modules to deploy 
ERROR: Failed to run plugin: qt (exit code: 1) 
```
It says that it's using qmake despite the fact that my project uses cmake. How can I use linuxdeploy-plugin-qt to deploy my cmake project?

**Comment by TheAssassin** [comment]
Your assumption is wrong. It uses qmake to detect some Qt paths, that's it. It is deploying your CMake project already.

The plugin wants to deploy Qt 5.12.8, but you intend to use Qt 6. You need to tell linuxdeploy-plugin-qt about your other Qt. You can do so by `export QMAKE=~/Qt-6.2/6.2.0/gcc_64/bin/qmake` (that path was just guessed by me, you need to adjust it).

**Comment by rsevero** [comment]
@TheAssassin , you are right. Just to help someone that might stumble on this issue the correct qmake path on Qt 6.2.0 is ~/Qt-6.2/6.2.0/gcc_64/bin/qmake so `export QMAKE=~/Qt-6.2/6.2.0/gcc_64/bin/qmake`

Answer Edit: I will remember it for the next time

Answer Edit 2: I tried those exact instructions but the `make -j$(nproc)` step ends with errors complaining about tons of undeclared enums and functions that aren't a problem when I build through QT Creator.

Thanks!

**Comment by TheAssassin** [comment]
> Answer Edit 2: I tried those exact instructions but the make -j$(nproc) step ends with errors complaining about tons of undeclared enums and functions that aren't a problem when I build through QT Creator.

If Qt Creator uses CMake to build your project, it might just inject a couple of library paths via flags. In any case, I'd recommend you to fix those issues at the root, i.e., in CMake.

Does the deployment work now? If so, please close this issue.

**Comment by rsevero** [comment]
> If Qt Creator uses CMake to build your project, it might just inject a couple of library paths via flags. In any case, I'd recommend you to fix those issues at the root, i.e., in CMake.

I would love to do it but have no idea how. Do you have any pointers?

> Does the deployment work now? If so, please close this issue.

Yes, after some icon file trouble I finally made my AppImage file.

Thanks!!

**Comment by TheAssassin** [comment]
As always, without any information, I could at most guess. But I don't want to do that. You can join the AppImage IRC channel to find people who use CMake as well. https://docs.appimage.org/contact.html
