### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by axelspoerl** [linuxdeploy/linuxdeploy-plugin-qt#99]
Can't build since yesterday's new release. Any help is greately appreciated.

axel@jupiter:~/Downloads/linuxdeploy-plugin-qt/build> cmake .. 
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'gtest>=1.11.0'
--   Found gtest, version 1.11.0
-- [cmake-scripts in linuxdeploy-plugin-qt] Using system gtest
CMake Error at lib/cmake-scripts/include-or-build-gtest.cmake:19 (add_library):
  add_library cannot create ALIAS target "gtest" because target
  "PkgConfig::__ld_gtest" is imported but not globally visible.

**Comment by TheAssassin** [comment]
You did not provide essential information such as your build system etc. Also I cannot reproduce this even with a system-provided gtest. Please make sure the submodules are up to date.

**Comment by axelspoerl** [comment]
@TheAssassin, sorry for that. I am trying to build (and have successfully built previous versions) on OpenSuSE Leap 15.3.
As gtest was initially missing, I have built the recent master from GitHUB (version 1.11.0). It is installed including sources.
I have cloned the linuxdeploy-plugin-qt repository with --recursive, hence the submodules should be up to date.
It looks to me more as if the current version expects gtest as a submodule. But with ---recursive, no gtest is pulled.

**Comment by TheAssassin** [comment]
gtest is pulled using CMake's `FetchContent` now if it is missing. The build scripts should use the system-wide gtest if available, though.

I'll try building on Leap myself.

**Comment by axelspoerl** [comment]
Okay, to use the system-wide gtest, you have to set the global imported property accordingly, right?
I just added `set_target_properties(PkgConfig::${prefix} PROPERTIES IMPORTED_GLOBAL TRUE)` at line 19 of include-or-build-gtest.cmake. Not sure if this is the most elegant place to put it, but it works now.

It hangs again just after having found gtest and claims that it does not find Boost (regex + filesystem). Both is installed system-wide (1.66.0).

-- [cmake-scripts in linuxdeploy-desktopfile] target gtest found, not setting up again
-- [linuxdeploy-desktopfile] Test test_desktopfile is excluded from ALL, not adding as test
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find Boost (missing: filesystem regex) (found version "1.66.0")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindBoost.cmake:2145 (find_package_handle_standard_args)
  lib/linuxdeploy/src/CMakeLists.txt:9 (find_package)

**Comment by TheAssassin** [comment]
I'm trying to build it myself in a container at the moment. Mind to join the AppImage IRC channel? https://docs.appimage.org/contact.html

**Comment by axelspoerl** [comment]
Joined.
